CREATE USER KH_SEMI IDENTIFIED BY KH_SEMI; -- 공용 계정 생성
GRANT RESOURCE, CONNECT TO KH_SEMI; -- 권한 설정
GRANT CREATE VIEW TO KH_SEMI; -- View 권한 추가 설정

-- Recruit Part DB 구축

-- Recruitment Table
CREATE TABLE RECRUITMENT (
    R_TITLE VARCHAR(30) PRIMARY KEY,
    R_CODE VARCHAR(30),
    R_START DATE,
    R_END DATE,
    R_TIME VARCHAR(20),
    R_CONTENT1 VARCHAR(1024),
    R_CONTENT2 VARCHAR(1024),
    R_CONTENT3 VARCHAR(1024),
    R_CONTENT4 VARCHAR(1024),
    R_CONTENT5 VARCHAR(1024),
    R_CONTENT6 VARCHAR(1024)
);

DESC RECRUITMENT;

COMMENT ON COLUMN RECRUITMENT.R_TITLE IS '공고명';
COMMENT ON COLUMN RECRUITMENT.R_CODE IS '직무구분';
COMMENT ON COLUMN RECRUITMENT.R_START IS '공고시작일';
COMMENT ON COLUMN RECRUITMENT.R_END IS '공고종료일';
COMMENT ON COLUMN RECRUITMENT.R_TIME IS '공고종류';
COMMENT ON COLUMN RECRUITMENT.R_CONTENT1 IS '공고소개';
COMMENT ON COLUMN RECRUITMENT.R_CONTENT2 IS '주요업무';
COMMENT ON COLUMN RECRUITMENT.R_CONTENT3 IS '자격요건';
COMMENT ON COLUMN RECRUITMENT.R_CONTENT4 IS '우대사항';
COMMENT ON COLUMN RECRUITMENT.R_CONTENT5 IS '혜택및복지';
COMMENT ON COLUMN RECRUITMENT.R_CONTENT6 IS '기타사항';

ALTER TABLE RECRUITMENT 
MODIFY (R_CODE NOT NULL, R_START NOT NULL, R_END NOT NULL, R_TIME NOT NULL);

-- RecruitMember Table
CREATE TABLE RECRUIT_MEMBER (
    RM_ID NUMBER PRIMARY KEY,
    RM_NAME VARCHAR(30),
    RM_PHONE VARCHAR(30),
    RM_EDUCATION VARCHAR(100),
    RM_CAREER VARCHAR(200),
    RM_EMAIL VARCHAR(50),
    RM_PASSWORD VARCHAR(30)
);

DESC RECRUIT_MEMBER;

COMMENT ON COLUMN RECRUIT_MEMBER.RM_ID IS '지원자번호';
COMMENT ON COLUMN RM_NAME.RM_ID IS '성명';
COMMENT ON COLUMN RECRUIT_MEMBER.RM_PHONE IS '연락처';
COMMENT ON COLUMN RECRUIT_MEMBER.RM_EDUCATION IS '학력사항';
COMMENT ON COLUMN RECRUIT_MEMBER.RM_CAREER IS '경력사항';
COMMENT ON COLUMN RECRUIT_MEMBER.RM_EMAIL IS '이메일';
COMMENT ON COLUMN RECRUIT_MEMBER.RM_PASSWORD IS '비밀번호';

ALTER TABLE RECRUIT_MEMBER 
MODIFY (RM_NAME NOT NULL, RM_PHONE NOT NULL, RM_EDUCATION NOT NULL, 
RM_CAREER NOT NULL, RM_EMAIL NOT NULL, RM_PASSWORD NOT NULL);

-- RecruitStatus Table
DROP TABLE RECRUIT_STATUS;

CREATE TABLE RECRUIT_STATUS (
    RS_ID NUMBER PRIMARY KEY,
    RS_STATE VARCHAR(20)
);

COMMENT ON COLUMN RECRUIT_STATUS.RS_ID IS '지원번호';
COMMENT ON COLUMN RECRUIT_STATUS.RS_STATE IS '지원상태';

ALTER TABLE RECRUIT_STATUS 
ADD R_TITLE VARCHAR(30);

ALTER TABLE RECRUIT_STATUS 
ADD CONSTRAINT FK_R_TITLE FOREIGN KEY(R_TITLE) REFERENCES RECRUITMENT(R_TITLE);

ALTER TABLE RECRUIT_STATUS 
ADD RM_ID NUMBER;

ALTER TABLE RECRUIT_STATUS 
ADD CONSTRAINT FK_RS_ID FOREIGN KEY(RM_ID) REFERENCES RECRUIT_MEMBER(RM_ID);

ALTER TABLE RECRUIT_STATUS
RENAME CONSTRAINT FK_RS_ID TO FK_RS_RM_ID;

COMMENT ON COLUMN RECRUIT_STATUS.R_TITLE IS '공고명';
COMMENT ON COLUMN RECRUIT_STATUS.RM_ID IS '지원자번호';

-- Attachment Table
CREATE TABLE ATTACHMENT (
    FILE_NO NUMBER PRIMARY KEY,
    REF_NO NUMBER,
    ORIGIN_NAME VARCHAR(200),
    CHANGE_NAME VARCHAR(200),
    UPLOAD_DATE DATE,
    FILE_PATH VARCHAR(1000)
);

COMMENT ON COLUMN ATTACHMENT.FILE_NO IS '파일번호';
COMMENT ON COLUMN ATTACHMENT.REF_NO IS '참조파트번호'; -- 1 공고 2 강의 3 펀딩 4 회원
COMMENT ON COLUMN ATTACHMENT.ORIGIN_NAME IS '파일원본명';
COMMENT ON COLUMN ATTACHMENT.CHANGE_NAME IS '파일수정명';
COMMENT ON COLUMN ATTACHMENT.UPLOAD_DATE IS '업로드일';
COMMENT ON COLUMN ATTACHMENT.FILE_PATH IS '저장폴더경로';


-- Portfolio Table
DROP TABLE PORTFOLIO;

CREATE TABLE PORTFOLIO (
    P_NO NUMBER PRIMARY KEY,
    FILE_NO NUMBER,
    RM_ID NUMBER,
    CONSTRAINT FK_FILE_NO FOREIGN KEY(FILE_NO) REFERENCES ATTACHMENT(FILE_NO),
    CONSTRAINT FK_RM_ID FOREIGN KEY(RM_ID) REFERENCES RECRUIT_MEMBER(RM_ID)
);

COMMENT ON COLUMN PORTFOLIO.P_NO IS '첨부파일번호';
COMMENT ON COLUMN PORTFOLIO.FILE_NO IS '파일번호';
COMMENT ON COLUMN PORTFOLIO.RM_ID IS '지원자번호';

CREATE SEQUENCE SEQ_RM_NO;
CREATE SEQUENCE SEQ_RS_NO;
CREATE SEQUENCE SEQ_P_NO;
